version: "3"
services:
  db:
    image: postgres
    container_name: "pg_container"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    ports:
      - "60703:5432"
    volumes:
      - ".db:/var/lib/postgresql/data/"

  bi:
    image: metabase/metabase
    ports:
      - "63811:3000"
    links:
      - db